name: SDK Core Build

on:
  push:
    paths:
      - 'core/**'
      - 'build.gradle.kts'
      - '.github/workflows/core-build.yaml'

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Build and lint
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: core:assemble
