name: Release Branch Cut

on:
  push:
    branches:
      - 'release/**'

jobs:
  bump-versions:
    runs-on: macos-11
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Set Environment Variables
        run: |
          if [[ $GITHUB_REF =~ release/(.*)(-v) ]]; then
              sdk_name=${BASH_REMATCH[1]}
              rel_version=${GITHUB_REF#*-v}
              echo "sdk_name=$sdk_name" >> "$GITHUB_ENV"
              echo "rel_version=$rel_version" >> "$GITHUB_ENV"
          else
              echo "Unable to parse sdk_name and version from GITHUB_REF: $GITHUB_REF"
              exit 1
          fi
      - name: Bump Version
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: "${{ env.sdk_name }}:bumpVersion -PnewVersion=${{ env.rel_version }}"
      - name: Build
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: "${{ env.sdk_name }}:assemble"
      - name: Merge version updates
        run: git push
      - name: Merge into develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          PR_URL=`gh pr create --title "Merge $branch_name into develop" \
            --body "This PR was automatically created by the release branch cut workflow.\nSDK=${{ env.sdk_name }}\nVERSION=${{ env.rel_version }}"\
            --base develop\
            --head $branch_name\
            --assignee ${{ github.event.pusher.name }}`
          gh pr merge $PR_URL --auto
      - name: Create Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          gh pr create --title "Merge $branch_name into main" \
            --body "This PR was automatically created by the release branch cut workflow.\nSDK=${{ env.sdk_name }}\nVERSION=${{ env.rel_version }}"\
            --base main\
            --head $branch_name\
            --assignee ${{ github.event.pusher.name }}
